In [1]:
import numpy as np

In [6]:
#Creating an numpy array
x = np.array([1,2,4,5]) #This is an one array
x = np.array([[1,2,3,4],[5,6,7,8]]) #This is 2-d numpy array

#Now creating n-dimension numpy array
x = np.array([1,2,3,4],ndmin=10)
print(x.ndim)

10


In [14]:
#filling element with 0
y = np.zeros(3) #It will create 1-d array filled with 0 of length 3
y = np.ones(5)


In [16]:
#now creating numpy array filled with 1 at diagonal
arr = np.eye(3) #create 3*3 matrix filled with 1 at diagonal and rest filled with 0
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
#use of linspace function in python to create an array with common difference constant
z = np.linspace(0,20,5)

#now doing same thing with using arange function 
z = np.arange(0,15,5)
z

array([ 0,  5, 10])