In [3]:
import numpy as np

print(np.__version__)

1.23.0


In [3]:
#create 1-d array from 0 to 9
x = np.array([i for i in range(0,10)])


In [7]:
# create 3*3 matrix of all true
x = np.full((3,3),True,dtype=bool)

In [21]:
#extract all the odd number from array
x = np.array([i for i in range(0,10)])
final = []
len(x)
for i in range(0,len(x)):
    if x[i]%2!=0 :
        final.append(x[i])

final

[1, 3, 5, 7, 9]

In [23]:
#Replace all odd number with -1
x = np.array([i for i in range(0,10)])
x[x%2!=0] = -1
x

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [25]:
#Replace all the odd number with -1 without changing the original array
x = np.array([i for i in range(0,10)])
cp = x.copy()
cp[cp%2!=0] = -1
cp

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [34]:
#converting 1-d array with 2-d array
x = np.arange(10)
var1 = x[:5]
var2 = x[5:]

final = np.vstack((var1,var2))

In [37]:
x = np.arange(15)
y = np.where(x%2==0,-1,x)

intersection = np.intersect1d(x,y)
intersection

array([ 1,  3,  5,  7,  9, 11, 13])

In [41]:
#remove the common element present in an array a
x = np.arange(10)
y = np.array([i for i in range(4,15)])

final = np.setdiff1d(x,y,assume_unique=True)
final

array([0, 1, 2, 3])

In [42]:
#using split function
x = np.arange(10)
y = x[1:4]
y

array([1, 2, 3])

In [44]:
#element wise addition of two numpy array
x = np.arange(0,12,2)
y = np.array([i for i in range(0,6)])

var = np.add(x,y)
var

array([ 0,  3,  6,  9, 12, 15])

In [48]:
#print the identity matrix we will use eye() function of numpy to get identity  matrix
x = np.eye(3,3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
#now again using full with some certian condition
x = np.arange(0,10)
y = np.where(x%2==0,True,x)
y

array([1, 1, 1, 3, 1, 5, 1, 7, 1, 9])

In [16]:
#Filter out odd element from the numpy array , a better syntactical sugar
x = np.arange(5,20)

mask = x%2!=0
print(x[mask])

[ 5  7  9 11 13 15 17 19]


In [23]:
#pracitse
x = np.array([4,2,5,7,3,7,3,1])
x.sort()
#take out those number which are divided by 7 or 3
mask = x%3==0
mask

array([False, False,  True,  True, False, False, False, False])

In [30]:
#using shuffle and unique function
x = np.array([1,2,3,4,5])

np.random.shuffle(x)
x

array([1, 5, 2, 4, 3])

In [38]:
#practise for random shuffle and usage of unique function
x = np.array([1,1,1,3,3,4,5,6,7])

np.random.shuffle(x)
x = np.unique(x,return_counts=True)
x

(array([1, 3, 4, 5, 6, 7]), array([3, 2, 1, 1, 1, 1]))

In [41]:
#let work on insert and deleteion of the element from numpy arrray
x = np.array([i for i in range(0,10)])
x = np.insert(x,(1,2),-1)
x

array([ 0, -1,  1, -1,  2,  3,  4,  5,  6,  7,  8,  9])

In [52]:
#now we will use delete function in numpy
x = np.array([1,2,3,4,5])
x = np.insert(x,(1,2),-1)
print(x)
x = np.delete(x,1)
x = np.delete(x,2)
print(x)

[ 1 -1  2 -1  3  4  5]
[1 2 3 4 5]


In [1]:
#now we will understand matrix function and its usecase
#dont confuse with matrix and n-dimensional array
x = np.matrix([[1,2],[3,4]])
y = np.matrix([[1,2],[3,4]])

print("Here is our dot product of these two matirces\n",np.dot(x,y))
print("Here we get our transpose of the matrix\n",np.transpose(x))
print("here we will print our inverse of the matrix\n",np.linalg.inv(x))
print("Here we will print determinant of the matrix\n",np.linalg.det(x))

NameError: name 'np' is not defined

In [11]:
#reshape function 
import numpy as np
x = np.array([1,2,3,4])
x[x%2!=0]
x

array([1, 2, 3, 4])